### ISSUE TITLE
Config example

### ISSUE THREAD

**Issue by dieugab** [stuart-c/homeassistant-switchbot#3]
Is it possible to try this custom component yet, and if so: what should the config file look like?

**Comment by stuart-c** [comment]
No config needed. All done via the UI

**Comment by dieugab** [comment]
Cool, got it working, thanks!

**Comment by stuart-c** [comment]
It would be great to hear what you think...

**Comment by almzro3e** [comment]
I have added the cloud but still it won't read my devices, current devices are hub and meter
